// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlPvjYblBic4zQNwgxYWh9Etr4WihiCuY',
    appId: '1:364119963723:web:8db39a358dfcebe252b5ce',
    messagingSenderId: '364119963723',
    projectId: 'e-commerce-app-clean-arch',
    authDomain: 'e-commerce-app-clean-arch.firebaseapp.com',
    storageBucket: 'e-commerce-app-clean-arch.firebasestorage.app',
    measurementId: 'G-EMKM0BC1ZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnOJbJ_v7GegCDWSIBuc8s3ZwyPE1RxZ4',
    appId: '1:364119963723:android:0f0f261c93fb401a52b5ce',
    messagingSenderId: '364119963723',
    projectId: 'e-commerce-app-clean-arch',
    storageBucket: 'e-commerce-app-clean-arch.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqMq-FXHmg17XQ3GqX3WgO4OrTQYHY_4M',
    appId: '1:364119963723:ios:64b1e817f7167f4352b5ce',
    messagingSenderId: '364119963723',
    projectId: 'e-commerce-app-clean-arch',
    storageBucket: 'e-commerce-app-clean-arch.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceAppcleanArchFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqMq-FXHmg17XQ3GqX3WgO4OrTQYHY_4M',
    appId: '1:364119963723:ios:64b1e817f7167f4352b5ce',
    messagingSenderId: '364119963723',
    projectId: 'e-commerce-app-clean-arch',
    storageBucket: 'e-commerce-app-clean-arch.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceAppcleanArchFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlPvjYblBic4zQNwgxYWh9Etr4WihiCuY',
    appId: '1:364119963723:web:cb89fc381716d22352b5ce',
    messagingSenderId: '364119963723',
    projectId: 'e-commerce-app-clean-arch',
    authDomain: 'e-commerce-app-clean-arch.firebaseapp.com',
    storageBucket: 'e-commerce-app-clean-arch.firebasestorage.app',
    measurementId: 'G-R6ZVTSE07G',
  );
}
